name: build_apk
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: GitGuardian
        uses: GitGuardian/ggshield-action@v1.14.4
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: ./build/app/outputs/apk/release/app-release.apk
